# Generated by Django 3.0.1 on 2020-02-12 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='content')),
                ('date', models.DateTimeField(verbose_name='date')),
                ('sender_id', models.CharField(max_length=100, verbose_name='sender id')),
                ('sender_username', models.CharField(max_length=100, verbose_name='sender username')),
                ('sender_name', models.CharField(max_length=100, verbose_name='sender name')),
                ('is_group', models.BooleanField(verbose_name='is group')),
                ('channel_username', models.CharField(max_length=100, verbose_name='channel username')),
                ('channel_name', models.CharField(max_length=100, verbose_name='channel name')),
                ('source', models.CharField(max_length=2, verbose_name='source')),
                ('stock_symbol', models.CharField(max_length=20, verbose_name='stock symbol')),
                ('sentiment', models.CharField(max_length=6, verbose_name='sentiment')),
                ('like_count', models.IntegerField(verbose_name='like count')),
                ('parent_content', models.TextField(verbose_name='parent content')),
                ('version', models.CharField(max_length=2, verbose_name='version')),
            ],
        ),
    ]
