# Generated by Django 3.0.1 on 2020-02-12 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackendApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='channel_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='channel name'),
        ),
        migrations.AlterField(
            model_name='post',
            name='like_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='like count'),
        ),
        migrations.AlterField(
            model_name='post',
            name='parent_content',
            field=models.TextField(blank=True, null=True, verbose_name='parent content'),
        ),
        migrations.AlterField(
            model_name='post',
            name='sender_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='sender name'),
        ),
    ]
