# Generated by Django 3.1 on 2020-08-17 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messageId', models.IntegerField()),
                ('content', models.TextField()),
                ('messageDate', models.DateTimeField()),
                ('elasticPushDate', models.DateTimeField()),
                ('senderId', models.IntegerField()),
                ('senderUsername', models.CharField(max_length=200)),
                ('senderName', models.CharField(max_length=200)),
                ('isGroup', models.BooleanField()),
                ('channelId', models.IntegerField()),
                ('channelName', models.CharField(max_length=200)),
                ('channelUsername', models.CharField(max_length=200)),
                ('parentId', models.IntegerField()),
                ('likeCount', models.IntegerField()),
                ('source', models.CharField(choices=[('telegram', 'Telegram'), ('sahamyab', 'Sahamyab')], max_length=100)),
                ('stock', models.CharField(max_length=100)),
                ('sentiment', models.CharField(choices=[('neutral', 'Neutral'), ('negative', 'Negative'), ('positive', 'Positive')], max_length=100)),
                ('image', models.TextField()),
                ('version', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['messageId'],
            },
        ),
    ]
