# Generated by Django 3.1 on 2020-08-17 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='channelUsername',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='likeCount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='parentId',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='senderUsername',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
